package com.ahmed.artify.artsy.Artwork

data class Artwork(val id: String,
                   val slug: String,
                   val created_at: String,
                   val updated_at: String,
                   val title: String,
                   val category: String,
                   val medium: String,
                   val date: String,
                   val dimensions: Dimensions,
                   val published: Boolean,
                   val website: String,
                   val signature: String,
                   val series: String,
                   val provenance: String,
                   val literature: String,
                   val exhibition_history: String,
                   val collecting_institution: String,
                   val additional_information: String,
                   val image_rights: String,
                   val blurb: String,
                   val unique: Boolean,
                   val cultural_maker: Any?,
                   val iconicity: Double,
                   val can_inquire: Boolean,
                   val can_acquire: Boolean,
                   val can_share: Boolean,
                   val sale_message: Any?,
                   val sold: Boolean,
                   val visibility_level: String,
                   val image_versions: List<String>,
                   val _links: ArtworkLinks,
                   val _embedded: ArtworkEmbedded)
